/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'alpar' at '11/11/16 8:39 AM' with Gradle 3.1
 *
 * @author alpar, @date 11/11/16 8:39 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
